#General
seed: 4
workers: 8
missing_rate: 0
device: '0'
dataset_dir: "./datasets"
dataset_name: LandUse-21 #Caltech101-20 Scene-15 LandUse-21 BDGP Fashion
batch_size: 256
learning_rate: 0.0001


#Model
model_kwargs:
  Encoder:
    arch: [500, 2000, 1000, 128]
    activation: False
    function: relu  #sigmoid leakyrelu tanh relu
    batchnorm: False
  Decoder:
    arch: [128, 1000, 2000, 500]
    activation: False
    function: relu  #sigmoid leakyrelu tanh relu
    batchnorm: False


#Pretrain
isPretrain: Ture
Pretrain_p:
  p_epoch: 200
  p_interval: 200
  pretrain_path: ./checkpoints/Scene-15_model.pkl  #Caltech101-20 Scene-15 LandUse-21 BDGP Fashion
  pretrain_save: ./runs/Scene-15.xls

#Robust Learning
second_stage:
  r_threshold: 2
  r_lr: 0.01
  r_momentum: 0.9
  r_weight_decay: 0.0005
  r_epoch: 1000
  r_bacth_size: 256

